### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by fedmich** [AlexeyBarabash/25th-brave-sync-word#1]
Just wanted to say **Thank you** for making this.
It helped me recover some of my bookmarks from my different browser profiles.

**Comment by Enigma1309** [comment]
Yes i lost my /home directory yesterday but i had sync code, i tried to login and it didn't worked..
then i saw [this](https://community.brave.com/t/my-sync-code-has-expired/499464) thread ,

Thank you so much it worked :D

**Comment by AlexeyBarabash** [comment]
Thanks guys for the feedback.

I just want to mention again, that it is non-official way and can stop work at any time.
One of the possible cases - we are planning to cleanup the old chains which were inactive for a long period of time.
So please don't use the Sync as a backup solution.

**Comment by Enigma1309** [comment]
Your efforts are appreciated

> we are planning to cleanup the old chains which were inactive for a long period of time.
So please don't use the Sync as a backup solution.

If it ever happens i'll ditch Brave and switch to Firefox (vertical tabs are the reason i'm holding back to brave)

**Comment by Enigma1309** [comment]
BTW can you please explain me how were you able to get [this](https://github.com/AlexeyBarabash/25th-brave-sync-word/blob/7a498884488e832a15381759d07742b21fcafaf8/index.html#L6) line of code, and how it's still working after 2 years?
Thanks in advanced

**Comment by AlexeyBarabash** [comment]
@Enigma1309 
> BTW can you please explain me how were you able to get [this](https://github.com/AlexeyBarabash/25th-brave-sync-word/blob/7a498884488e832a15381759d07742b21fcafaf8/index.html#L6) line of code, and how it's still working after 2 years? Thanks in advanced

this line is taken from bip39 spec
https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

it still works because it is the same code js implementation as Brave Sync client has
https://github.com/brave/brave-core/blob/master/components/brave_sync/time_limited_words.cc#L128

**Comment by Enigma1309** [comment]
Thank you ️!! ❤️
